# Generated by Django 5.0.1 on 2024-01-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_orders', '0003_alter_movieorder_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieorder',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
